### ISSUE TITLE
Version in readme wrong?

### ISSUE THREAD

**Issue by jitsatya** [sopranopillow/fluentui-nextjs-appdir-plugin#3]
Version compat in readme says
For versions < 14.1.2 please use 1.0.5 otherwise there wil be issues with the swc_core version causing rust to panic.
when I do 
`npm install fluentui-next-appdir-directive@1.0.5`
It gives error 
`npm error notarget No matching version found for fluentui-next-appdir-directive@1.0.5. `

Is the version in readme wrong? how do I install a version that is compatible for "next": "^14.0.2"

**Comment by jitsatya** [comment]
Seems like the version is "fluentui-next-appdir-directive": "^0.1.5" for < 14.1.2, Please update it in readme @sopranopillow

**Comment by sopranopillow** [comment]
will do, thanks for the issue!

**Comment by sopranopillow** [comment]
@jitsatya, updated version!

```md
### Version compat
- For versions `< 14.1.2` please use 0.1.5 otherwise there wil be issues with the swc_core version causing rust to panic.
- For version `>= 14.1.2` please use 0.1.7 for the same reason as above, 0.1.7 introduced version `0.90.*` of swc_core which makes it compatible with the versions used in `<= 14.1.2`.
```
