### ISSUE TITLE
Popovers not rendering consistently after upgrade to next 14.2 

### ISSUE THREAD

**Issue by ewylie25** [sopranopillow/fluentui-nextjs-appdir-plugin#4]
Hi

Not sure if this could be due to this plug in or not but... after upgrading to nextjs 14.2.6 and 0.1.7 of this plugin, we noticed that the popovers do not consistently render. My team tends to develop on windows machines but deploy to linux containers. The popovers work fine with dev and production builds in the linux containers but do not render when we do local development on windows machines. Everything works with nextjs 14.1.1 and 0.1.5 of the plugin.

What we noticed is that the fluent provider which wraps the popover surface and react portal are missing from the DOM when it does not render. I'm not sure if this is an issue with the plugin or an issue with fluent v9.

**Comment by sopranopillow** [comment]
@ewylie25  I've seen a similar issue before, but in normal Fluent (no SSR/RSC). This usually means you have duplicate packages or different versions of fluent. Any chance you could double check that?

**Comment by sopranopillow** [comment]
closing as stale, feel free to reopen if investigation is still needed. If you reopen, I would appreciate checking what I mentioned before just as a troubleshooting step :)
